name: card
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cudatoolkit=11.1
  - ffmpeg
  - freetype
  - giflib
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - libffi
  - libiconv
  - libpng
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openssl
  - patsy
  - pillow
  - pip
  - python=3.8.12
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - setuptools
  - six
  - sqlite
  - statsmodels
  - tk
  - torchaudio
  - torchvision
  - typing_extensions
  - wheel
  - xz
  - zlib
  - zstd
  - absl-py
  - anyio
  - argon2-cffi
  - astroid
  - attrs
  - babel
  - backcall
  - bleach
  - cachetools
  - cffi
  - charset-normalizer
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - dill
  - entrypoints
  - flake8
  - fonttools
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - idna
  - importlib-metadata
  - importlib-resources
  - inflect
  - ipykernel
  - ipython
  - isort
  - jedi
  - jinja2
  - joblib
  - json5
  - jsonschema
  - jupyterlab
  - kiwisolver
  - lazy-object-proxy
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-inline
  - mccabe
  - mistune
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - oauthlib
  - packaging
  - pandas
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - platformdirs
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pydocstyle
  - pyflakes
  - pygments
  - pylama
  - pylint
  - pyparsing
  - pyrsistent
  - pyyaml
  - pyzmq
  - requests
  - requests-oauthlib
  - rsa
  - scikit-learn
  - scipy
  - send2trash
  - setuptools-scm
  - sniffio
  - snowballstemmer
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - terminado
  - testpath
  - threadpoolctl
  - tomli
  - tomlkit
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wrapt
  - zipp
  - pip:
    - jupyter-core
    - ipython-genutils
    - jupyterlab-server
    - prometheus-client
    - jupyter-client
    - jupyter-server
    - torch-tb-profiler
    - jupyterlab-pygments
